#!/usr/bin/env bash

# Forked from https://github.com/seh/rules_cue/blob/main/cue/cue-run-from-runfiles

# Copy-pasted from the Bazel Bash runfiles library v2.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e

function usage() {
  printf "usage: %s [-c cue_cache_directory] [-i instance_path] [-m module_file] [-p package_name] cue_tool cue_command extra_args_file output_file [args...]\n" "$(basename "${0}")" 1>&2
  exit 2
}

cue_cache_directory=
instance_path=
module_file=
package_name=

function parse_args() {
  while getopts i:m:p: name
  do
    case "${name}" in
      c) cue_cache_directory="${OPTARG}";;
      i) instance_path="${OPTARG}";;
      h) usage;;
      m) module_file="${OPTARG}";;
      p) package_name="${OPTARG}";;
      ?) usage;;
    esac
  done
  if [ -n "${cue_cache_directory}" ] && [ ! -d "${cue_cache_directory}" ]; then
      printf "%s: specified CUE cache directory \"%s\" does not exist\n" "$(basename "${0}" "${cue_cache_directory}")" 1>&2
      exit 1
  fi
  if [ -n "${instance_path}" ] && [ -z "${module_file}" ]; then
      printf "%s: specifying a CUE instance path requires specifying a module path\n" "$(basename "${0}")" 1>&2
      exit 1
  fi
  if [ -n "${package_name}" ] && [ -z "${instance_path}" ]; then
      printf "%s: specifying a CUE package name requires specifying an instance path\n" "$(basename "${0}")" 1>&2
      exit 1
  fi
}

parse_args "${@}"
shift $((OPTIND - 1))

cue=$1; shift
command=$1; shift
extra_args_file=$1; shift
output_file=$1; shift

oldwd="${PWD}"

if [ -n "${module_file}" ]; then
  adjusted_module_file="$(rlocation ${module_file})"
  if [ -z "${adjusted_module_file}" ]; then
    echo >&2 "No runfile path available for module file path \"${module_file}\"."
    exit 1
  fi
  module_path="$(dirname $(dirname ${adjusted_module_file}))"
  cd "${module_path}"
fi

# Since we don't have access to the "HOME" environment variable here
# (barring use of the "--action-env" command-line flag), we must tell
# CUE where to store its cache explicitly.
if [ -n "${cue_cache_directory}" ]; then
  export CUE_CACHE_DIR="${cue_cache_directory}"
elif [ -z "${HOME:-}" ]; then
  cue_cache_directory="$(mktemp -d -t cue-XXXXXX)"
  trap "rm -rf '${cue_cache_directory}'" EXIT
  export CUE_CACHE_DIR="${cue_cache_directory}"
fi

"${oldwd}/${cue}" "${command}" --outfile "${oldwd}/${output_file}" \
  ${instance_path}${package_name:+:${package_name}} \
  $(< "${oldwd}/${extra_args_file}") \
  "${@-}"
